// Using SendGrid integration blueprint
import { MailService } from '@sendgrid/mail';

if (!process.env.SENDGRID_API_KEY) {
  console.warn("SENDGRID_API_KEY environment variable not set - email notifications disabled");
}

const mailService = new MailService();
if (process.env.SENDGRID_API_KEY) {
  mailService.setApiKey(process.env.SENDGRID_API_KEY);
}

interface EmailParams {
  to: string;
  from: string;
  subject: string;
  text?: string;
  html?: string;
}

export async function sendEmail(params: EmailParams): Promise<boolean> {
  if (!process.env.SENDGRID_API_KEY) {
    console.log('Email notification skipped - SendGrid not configured');
    return false;
  }

  try {
    await mailService.send({
      to: params.to,
      from: params.from,
      subject: params.subject,
      text: params.text || '',
      html: params.html || '',
    });
    console.log(`Email sent successfully to ${params.to}`);
    return true;
  } catch (error) {
    console.error('SendGrid email error:', error);
    return false;
  }
}

export async function sendTaskAssignmentNotification(
  assigneeEmail: string, 
  taskName: string, 
  projectName: string, 
  dueDate?: string | null
): Promise<boolean> {
  const subject = `New Task Assigned: ${taskName}`;
  const text = `You have been assigned a new task "${taskName}" in project "${projectName}".${dueDate ? ` Due date: ${dueDate}` : ''}`;
  const html = `
    <h2>New Task Assignment</h2>
    <p>You have been assigned a new task:</p>
    <ul>
      <li><strong>Task:</strong> ${taskName}</li>
      <li><strong>Project:</strong> ${projectName}</li>
      ${dueDate ? `<li><strong>Due Date:</strong> ${dueDate}</li>` : ''}
    </ul>
    <p>Please check your project management dashboard for more details.</p>
  `;

  return sendEmail({
    to: assigneeEmail,
    from: 'noreply@changemanagement.com', // Should be configured in environment
    subject,
    text,
    html
  });
}

export async function sendFlyerDistribution(
  recipientEmail: string,
  flyerTitle: string,
  flyerContent: string,
  projectName: string,
  distributionMethod: string = 'email'
): Promise<boolean> {
  const subject = `Important Communication: ${flyerTitle}`;
  
  // Clean content for text version
  const textContent = flyerContent.replace(/<[^>]*>/g, '').replace(/\n+/g, '\n\n');
  
  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background-color: #2E5266; color: white; padding: 20px; text-align: center;">
        <h1 style="margin: 0; font-size: 24px;">${flyerTitle}</h1>
        <p style="margin: 10px 0 0 0; font-size: 14px;">Change Initiative Communication</p>
      </div>
      
      <div style="padding: 30px; background-color: #ffffff;">
        <div style="color: #333333; line-height: 1.6; font-size: 16px;">
          ${flyerContent.split('\n').map(line => 
            line.trim() ? `<p style="margin-bottom: 15px;">${line.trim()}</p>` : ''
          ).join('')}
        </div>
      </div>
      
      <div style="background-color: #F8F9FA; padding: 20px; text-align: center; border-top: 1px solid #e9ecef;">
        <p style="margin: 0; color: #5A7684; font-size: 14px;">
          <strong>Project:</strong> ${projectName}<br>
          This communication was sent via ${distributionMethod} distribution.
        </p>
        <p style="margin: 10px 0 0 0; color: #5A7684; font-size: 12px;">
          Generated by Essayons Change Platform
        </p>
      </div>
    </div>
  `;

  return sendEmail({
    to: recipientEmail,
    from: process.env.FROM_EMAIL || 'noreply@changemanagement.com',
    subject,
    text: `${flyerTitle}\n\n${textContent}\n\nProject: ${projectName}\nSent via ${distributionMethod} distribution.\n\nGenerated by Essayons Change Platform`,
    html
  });
}

export async function sendBulkFlyerDistribution(
  recipients: string[],
  flyerTitle: string,
  flyerContent: string,
  projectName: string,
  distributionMethod: string = 'email'
): Promise<{ sent: number; failed: number; results: Array<{ email: string; success: boolean; error?: string }> }> {
  const results: Array<{ email: string; success: boolean; error?: string }> = [];
  let sent = 0;
  let failed = 0;

  // Send emails with rate limiting (SendGrid has rate limits)
  for (const email of recipients) {
    try {
      const success = await sendFlyerDistribution(email, flyerTitle, flyerContent, projectName, distributionMethod);
      if (success) {
        sent++;
        results.push({ email, success: true });
      } else {
        failed++;
        results.push({ email, success: false, error: 'Send failed' });
      }
      
      // Rate limiting: wait 100ms between emails to avoid hitting SendGrid limits
      await new Promise(resolve => setTimeout(resolve, 100));
    } catch (error) {
      failed++;
      results.push({ 
        email, 
        success: false, 
        error: error instanceof Error ? error.message : 'Unknown error' 
      });
    }
  }

  return { sent, failed, results };
}